language: rust

rust:
- stable

os:
  - linux

notifications:
  email: false

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
